language: node_js

node_js:
- '4.1'

install:
   - npm install hexo-cli -g
   - npm install

script:
   - hexo -version
   - hexo clean
   - hexo g
   - hexo deploy
 
before_script:
  - npm install -g gulp
 
script:
  - hexo -version
  - hexo clean
  - hexo g
  - hexo deploy
 
after_script:
  - cd ./public
  - git init
  - git config user.name "coder-caicai"
  - git config user.email "bj_ccz@sina.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle
 
branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: git@github.com:coder-caicai/coder-caicai.github.io.git

